# Generated by Django 5.1.1 on 2024-09-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_postd',
            new_name='date_posted',
        ),
    ]
